[commandDescriptions]
  about      = "Information about the bot"
  choose     = "Picks from a selection menu"
  discordfm  = "Plays music from discord.fm playlists"
  dump       = "Outputs the music queue as a json string"
  help       = "Shows command help"
  invite     = "Adds the bot to your server"
  jump       = "Skips to a time in the current song"
  move       = "Moves the bot to a different voice channel"
  nowplaying = "Shows the current song"
  pause      = "Pauses & resumes the song"
  play       = "Adds a song to the queue and begins playing"
  queue      = "Shows the song queue"
  radio      = "Streams UK radio stations"
  reorder    = "Changes the position of a song in the queue"
  repeat     = "Loops the current song"
  restart    = "Plays a song from the beginning"
  search     = "Searches for a song on youtube"
  shuffle    = "Shuffles the song queue"
  skip       = "Plays the next song in the queue"
  stop       = "Stops playing and leaves the voice channel"
  volume     = "Changes the music volume"

[radioStations]
  "Absolute Radio"        = "http://icy-e-bab-09-boh.sharp-stream.com/absoluteradio.mp3"
  "Absolute Radio 80s"    = "http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3.m3u"
  "AvtoRadio"             = "http://ic7.101.ru:8000/v3_1"
  "BBC 1Xtra"             = "http://www.listenlive.eu/bbc1xtra.m3u"
  "BBC Asian Network"     = "http://www.listenlive.eu/bbcasian.m3u"
  "BBC Radio 1"           = "http://www.listenlive.eu/bbcradio1.m3u"
  "BBC Radio 2"           = "http://www.listenlive.eu/bbcradio2.m3u"
  "BBC Radio 3"           = "http://www.listenlive.eu/bbcradio3.m3u"
  "BBC Radio 4"           = "http://www.listenlive.eu/bbcradio4.m3u"
  "BBC Radio 5 Live"      = "http://www.listenlive.eu/bbc5live.m3u"
  "BridgeFM"              = "http://icy-e-03-boh.sharp-stream.com/tcbridge.mp3"
  "CapitalFM Liverpool"   = "http://media-ice.musicradio.com/CapitalLiverpoolMP3.m3u"
  "CapitalFM South Wales" = "http://media-ice.musicradio.com/CapitalSouthWalesMP3"
  "Cima 100"              = "http://www.surfmusic.de/m3u/cima-100-fm,3447.m3u"
  "ClassicalFM"           = "http://media-ice.musicradio.com/ClassicFMMP3"
  "Derman Gibi Radyo"     = "http://yayin3.canlitv.com:9050/"
  "GGRadio.net"           = "http://sv.ggradio.net:8000/stream"
  "Happy Christmas Radio" = "http://streaming.radionomy.com/HappyChristmasradio"
  "Heart"                 = "http://media-ice.musicradio.com/HeartSouthWalesMP3"
  "Hive365"               = "http://stream.hive365.co.uk:8088/live"
  "ILoveRadio 1"          = "http://stream06.iloveradio.de/iloveradio1.mp3"
  "ILoveRadio 2"          = "http://stream06.iloveradio.de/iloveradio2.mp3"
  "KissFM"                = "http://icy-e-ba-09-boh.sharp-stream.com/kissnational.mp3"
  "Kiss Fresh"            = "http://icy-e-bl-06-cr.sharp-stream.com:8000/kissfresh.mp3?type=.flv"
  "Kisstory"              = "http://icy-e-bl-06-cr.sharp-stream.com:8000/kisstory.mp3?type=.flv"
  "Los40"                 = "http://19113.live.streamtheworld.com/LOS40.mp3"
  "M-1"                   = "http://stream.m-1.fm/M-1aacp"
  "NonStopPlay"           = "http://www.nonstopplay.com/site/media/pls/midband.pls"
  "NRK mP3"               = "http://nrk-mms-live.online.no/nrk_radio_mp3_aac_h"
  "Otvoreni"              = "http://50.7.130.2:13014/stream"
  "PowerFM"               = "http://icast.powergroup.com.tr/PowerFM/mpeg/128/home"
  "PowerHitRadio"         = "http://power-stream.data.lt:8000/PHR.mp3"
  "Radio 538"             = "http://vip-icecast.538.lw.triple-it.nl/RADIO538_MP3
  "Radio City"            = "http://icy-e-bl-09-boh.sharp-stream.com/city.mp3"
  "Radio Disney"          = "http://radio.domint.net:8026/"
  "Radio Nova Era"        = "http://centova.radios.pt:9478/stream"
  "Record Dance Radio"    = "http://air.radiorecord.ru:805/rr_320"
  "Radio Veronica"        = "http://8543.live.streamtheworld.com/VERONICACMP3"
  "RMF Maxxx"             = "http://195.150.20.242:8000/rmf_maxxx"
  "Smooth Radio"          = "http://media-ice.musicradio.com/SmoothSouthWalesMP3"
  "SwanseaSound"          = "http://gbradio.cdn.tibus.net/SWASS"
  "The Breeze"            = "http://stream5.radiomonitor.com/Breeze-Bristol-128"
  "TheWave"               = "http://gbradio.cdn.tibus.net/SWAWave"
  "TSF"                   = "http://tsfdirecto.tsf.pt/tsfdirecto.mp3"
